- name: Install Proxmox source
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
    state: present
    filename: pve-install-repo.list
    update_cache: no

- name: add GPG Key for Proxmox
  apt_key:
    url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    state: present

- name: update Cache
  apt:
    update_cache: yes
    upgrade: dist